config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/search', to: 'pages#search', as: 'search'

  resources :friends, only: [:index] do
    post 'follow', on: :member
    delete 'unfollow', on: :member
  end
  resources :profiles, only: [:show]
  root 'pages#home'
end

app/views/shared/_blocked.html.haml
.row
    .col-sm-4.offset-sm-4
        .card.profile
            .row.g-6
                .col-sm-4
                    =image_tag user.twitter_avatar_url, class: 'img-thumbnail', size: '150x150'
                .col-sm-8
                    .card-body
                        %h5.card-title
                            = user.twitter_handle

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "/"} BlockPartyIO
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      - if user_signed_in?
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item
            = link_to 'My Profile', profile_path(current_user), class: 'nav-link'
      = form_tag search_url, method: :get, class: 'd-flex' do |f| 
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search", name: 'q', value: params[:q]}/
        %button.btn.btn-outline-success{:type => "submit"} Search

app/views/shared/_profile.html.haml
.row
    .col-sm-4.offset-sm-4
        .card.profile
            .row.g-6
                .col-sm-4
                    =image_tag user.twitter_avatar_url, class: 'img-thumbnail', size: '150x150'
                    %p
                        %span.badge.bg-primary
                            = pluralize(user.following_count, 'following')
                        %span.badge.bg-primary
                            = pluralize(user.followers_count, 'followers')
                .col-sm-8
                    .card-body
                        %h5.card-title
                            = user.handle
                        %p.card-text
                            currently blocking
                            = pluralize(user.blocked_users.count, 'users')
                        - if user_signed_in? && user != current_user
                            %a.btn.btn-primary{ href: user_follow_path(user), method: 'post' }
                                Follow
                                = user.handle